import json
import subprocess
import sys
from tempfile import TemporaryDirectory, gettempdir
import unittest
from unittest.mock import patch
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

from scripts.verify_candidate import build_candidate_audit
import scripts.verify_candidate as candidate_verifier


def _candidate_integration_artifacts_present():
    required = (
        ROOT / "artifacts" / "deployment-readiness-report.json",
        ROOT / "artifacts" / "final-acceptance-gate.json",
        ROOT / "artifacts" / "review-package.json",
        ROOT / "artifacts" / "sealed" / "s0-acceptance" / "artifact-manifest.json",
    )
    handoffs = tuple((ROOT / "artifacts").glob("handoff-release-v*/handoff-manifest.json"))
    return all(path.is_file() for path in required) and bool(handoffs)


class CandidateVerifierTests(unittest.TestCase):
    @unittest.skipUnless(
        _candidate_integration_artifacts_present(),
        "release-candidate integration artifacts are generated by the CI release-audit step",
    )
    def test_read_only_candidate_audit_separates_local_and_external_state(self):
        completed = subprocess.run(
            [sys.executable, "scripts/verify_candidate.py", "--root", "."],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(completed.returncode, 0, completed.stderr)
        report = json.loads(completed.stdout)
        self.assertEqual(report["candidate_status"], "LOCAL_CANDIDATE_VERIFIED")
        self.assertEqual(report["closure_status"], "EXTERNAL_CLOSURE_PENDING")
        self.assertEqual(report["readiness_result"], "DEPLOYMENT_READINESS_BLOCKED")
        self.assertEqual(report["final_acceptance_result"], "FINAL_ACCEPTANCE_BLOCKED")
        self.assertEqual(
            next(item for item in report["checks"] if item["check_id"] == "LOCAL-PROFILE-01")["result"],
            "PASS",
        )
        self.assertEqual(report["active_profile"]["profile_id"], "workspace-local-candidate")
        self.assertEqual(report["latest_handoff"]["status"], "VERIFIED")
        self.assertEqual(
            next(item for item in report["checks"] if item["check_id"] == "LOCAL-SBOM-01")["result"],
            "PASS",
        )
        self.assertGreaterEqual(report["external_blocker_count"], 6)
        self.assertEqual(report["scenario_inventory"]["preflight_check_count"], 16)
        self.assertEqual(report["scenario_inventory"]["d2_runtime_case_count"], 34)
        self.assertEqual(report["scenario_inventory"]["blocked_r_fc_case_count"], 17)
        self.assertEqual(report["scenario_inventory"]["handler_manifest_case_count"], 34)
        for blocker in report["external_blockers"]:
            self.assertTrue(blocker["assertion"])
            self.assertTrue(blocker["observation"])
            self.assertEqual(blocker["severity"], "HARD_BLOCK")

        explicit = subprocess.run(
            [
                sys.executable,
                "scripts/verify_candidate.py",
                "--root",
                ".",
                "--profile",
                "deployment-profile.example.json",
                "--handoff-manifest",
                report["latest_handoff"]["manifest"],
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(explicit.returncode, 0, explicit.stderr)
        self.assertEqual(json.loads(explicit.stdout)["latest_handoff"]["status"], "VERIFIED")

    def test_explicit_handoff_outside_root_is_rejected(self):
        report = build_candidate_audit(ROOT, Path(gettempdir()) / "pmiri-outside-handoff-manifest.json")
        handoff_check = next(item for item in report["checks"] if item["check_id"] == "LOCAL-HANDOFF-01")
        self.assertEqual(handoff_check["result"], "FAIL")
        self.assertEqual(handoff_check["details"], "handoff_manifest_outside_project")

    def test_dependency_runtime_drift_invalidates_candidate(self):
        with patch.object(candidate_verifier, "verify_installed", return_value=["package_version_drift:attrs"]):
            report = build_candidate_audit(ROOT)
        reproducibility_check = next(item for item in report["checks"] if item["check_id"] == "LOCAL-REPRO-01")
        self.assertEqual(reproducibility_check["result"], "FAIL")
        self.assertEqual(report["candidate_status"], "LOCAL_CANDIDATE_INVALID")

    @unittest.skipUnless(
        _candidate_integration_artifacts_present(),
        "release-candidate integration artifacts are generated by the CI release-audit step",
    )
    def test_profile_drift_is_rejected(self):
        profile = json.loads((ROOT / "deployment-profile.example.json").read_text(encoding="utf-8"))
        profile["api"]["port"] += 1
        with TemporaryDirectory(dir=ROOT) as temporary:
            profile_path = Path(temporary) / "drifted-profile.json"
            profile_path.write_text(json.dumps(profile), encoding="utf-8")
            report = build_candidate_audit(ROOT, profile=profile_path)
        profile_check = next(item for item in report["checks"] if item["check_id"] == "LOCAL-PROFILE-01")
        self.assertEqual(profile_check["result"], "FAIL")
        self.assertIn("readiness_profile_fingerprint_mismatch", profile_check["details"])

    @unittest.skipUnless(
        _candidate_integration_artifacts_present(),
        "release-candidate integration artifacts are generated by the CI release-audit step",
    )
    def test_scenario_inventory_rejects_duplicate_authority_ids(self):
        mutations = (
            ("d2-runtime-candidate-report.json", "d2_runtime_candidate_contract_invalid", lambda value: value["cases"][1].__setitem__("scenario_id", value["cases"][0]["scenario_id"])),
            ("r-fc-blocked-candidate-report.json", "blocked_r_fc_inventory_contract_invalid", lambda value: value["cases"][0].__setitem__("check_id", value["cases"][1]["check_id"])),
        )
        for filename, expected_error, mutate in mutations:
            with self.subTest(filename=filename):
                original_loader = candidate_verifier._load_json

                def tampered_loader(path, *, _filename=filename, _mutate=mutate):
                    value, error = original_loader(path)
                    if value is not None and path.name == _filename:
                        value = json.loads(json.dumps(value))
                        _mutate(value)
                    return value, error

                with patch.object(candidate_verifier, "_load_json", side_effect=tampered_loader):
                    _, errors = candidate_verifier._validate_scenario_inventory(ROOT)
                self.assertIn(expected_error, errors)

    @unittest.skipUnless(
        _candidate_integration_artifacts_present(),
        "release-candidate integration artifacts are generated by the CI release-audit step",
    )
    def test_stale_handoff_is_rejected_against_current_source_tree(self):
        report = build_candidate_audit(
            ROOT,
            handoff_manifest=ROOT / "artifacts" / "handoff-release-v73" / "handoff-manifest.json",
        )
        handoff_check = next(item for item in report["checks"] if item["check_id"] == "LOCAL-HANDOFF-01")
        self.assertEqual(handoff_check["result"], "FAIL")
        self.assertTrue(str(handoff_check["details"]["reason"]).startswith("current_source_fingerprint_mismatch:"))

    @unittest.skipUnless(
        _candidate_integration_artifacts_present(),
        "release-candidate integration artifacts are generated by the CI release-audit step",
    )
    def test_sbom_drift_is_rejected(self):
        original_loader = candidate_verifier._load_json

        def tampered_loader(path, *, _original=original_loader):
            value, error = _original(path)
            if value is not None and path.name == "pmiri-sbom.spdx.json":
                value = json.loads(json.dumps(value))
                value["packages"][1]["versionInfo"] = "0.0.0"
            return value, error

        with patch.object(candidate_verifier, "_load_json", side_effect=tampered_loader):
            details, errors = candidate_verifier._validate_sbom(ROOT)
        self.assertEqual(details["path"], "artifacts/sbom/pmiri-sbom.spdx.json")
        self.assertIn("package_version_mismatch:attrs", errors)
        self.assertIn("sbom_not_deterministic_or_stale", errors)


if __name__ == "__main__":
    unittest.main()
