"""End-to-end local deployment and recovery smoke scenario.

This harness exercises only local synthetic data.  It proves that the
transactional store, recovery path, query surface and local control plane can
be assembled together; it never enables external network/provider access and
does not turn readiness into production approval.
"""

from __future__ import annotations

import json
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any, Mapping

from .canonical import is_sha256, sha256_json, utc_now
from .control_plane import SQLiteAuthenticationRegistry, SQLitePolicyEpoch, SQLiteRateLimiter, SQLiteReplayGuard
from .models import QueryRequest
from .readiness import default_profile, run_deployment_readiness, validate_readiness_report
from .sealing import seal_directory
from .runtime import LocalEvidenceRuntime
from .store import SQLiteStore


ARTIFACT_KIND = "PMIRI-DEPLOYMENT-SMOKE-REPORT"
REPORT_VERSION = "0.1"


class DeploymentSmokeError(ValueError):
    """Raised when the local deployment/recovery path cannot be proven."""


def _fingerprint(value: Any) -> str:
    return sha256_json(value)


def run_local_deployment_smoke(
    project_root: str | Path,
    *,
    fixture_root: str | Path | None = None,
    captured_at: str | None = None,
) -> dict[str, Any]:
    """Run the local ingest → backup → restore → query → readiness chain."""
    root = Path(project_root).resolve()
    fixture = Path(fixture_root or root / "fixtures" / "s0" / "project-alpha").resolve()
    if not fixture.is_dir() or root not in fixture.parents:
        raise DeploymentSmokeError("deployment_smoke_fixture_invalid")
    captured_at = captured_at or utc_now()

    with TemporaryDirectory(prefix=".pmiri-deployment-smoke-", dir=root) as temporary:
        smoke_root = Path(temporary)
        primary = SQLiteStore(smoke_root / "primary")
        primary.initialize()
        records = primary.ingest_directory("project-alpha", fixture)
        if len(records) != 3:
            raise DeploymentSmokeError("deployment_smoke_fixture_count_invalid")

        query_request = QueryRequest("deployment-smoke-query", "project-alpha", "release status", max_results=10)
        primary_result = LocalEvidenceRuntime(primary).query(query_request)
        if len(primary_result.evidence) != 3:
            raise DeploymentSmokeError("deployment_smoke_primary_query_invalid")

        backup = primary.backup_to(smoke_root / "backup")
        restored = SQLiteStore(smoke_root / "backup").restore_from_backup(smoke_root / "restored")
        restored_store = SQLiteStore(smoke_root / "restored")
        restored_result = LocalEvidenceRuntime(restored_store).query(query_request)
        if primary_result.structured() != restored_result.structured():
            raise DeploymentSmokeError("deployment_smoke_query_restore_mismatch")
        if backup["backup_fingerprint"] != restored["source_fingerprint"] or restored["source_fingerprint"] != restored["restored_fingerprint"]:
            raise DeploymentSmokeError("deployment_smoke_restore_fingerprint_mismatch")

        control_path = smoke_root / "control.db"
        SQLiteAuthenticationRegistry(control_path).initialize()
        SQLiteReplayGuard(control_path).initialize()
        SQLiteRateLimiter(control_path).initialize()
        SQLitePolicyEpoch(control_path).initialize()

        profile = default_profile()
        relative_smoke_root = smoke_root.relative_to(root).as_posix()
        profile["storage"]["root"] = relative_smoke_root + "/primary"
        profile["control_plane"]["path"] = relative_smoke_root + "/control.db"
        # Candidate artifacts are generated by separate CLI commands and may
        # have changed since the last manual seal. Refresh the canonical
        # local manifest here so the smoke is self-contained and never proves
        # readiness against a stale byte inventory.
        seal_directory(
            root,
            case_id="s0-acceptance",
            output_dir=root / "artifacts" / "sealed" / "s0-acceptance",
        )
        readiness = run_deployment_readiness(root, profile=profile, captured_at=captured_at)
        readiness_data = readiness.structured()
        readiness_errors = validate_readiness_report(readiness_data)
        if readiness_errors:
            raise DeploymentSmokeError("deployment_smoke_readiness_invalid:" + readiness_errors[0])
        local_blocked = [
            item["check_id"]
            for item in readiness_data["checks"]
            if item["category"] != "EXTERNAL_PREREQUISITE" and item["result"] != "READY"
        ]
        if local_blocked:
            raise DeploymentSmokeError("deployment_smoke_local_readiness_blocked:" + ",".join(local_blocked))

        unsigned = {
            "artifact_kind": ARTIFACT_KIND,
            "report_version": REPORT_VERSION,
            "status": "DEPLOYMENT_SMOKE_CANDIDATE",
            "project_root": root.as_posix(),
            "fixture": "fixtures/s0/project-alpha",
            "source_count": len(records),
            "primary_fingerprint": primary.canonical_fingerprint(),
            "backup_fingerprint": str(backup["backup_fingerprint"]),
            "restored_fingerprint": str(restored["restored_fingerprint"]),
            "query_evidence_count": len(primary_result.evidence),
            "query_fingerprint": _fingerprint(primary_result.structured()),
            "control_plane": "SQLITE_LOCAL_INITIALIZED",
            "readiness_status": readiness_data["overall_result"],
            "local_readiness_blocked_checks": local_blocked,
            "external_readiness_blocked_checks": [
                item["check_id"] for item in readiness_data["checks"] if item["category"] == "EXTERNAL_PREREQUISITE" and item["result"] == "BLOCKED"
            ],
            "external_access": "NOT_PERFORMED",
            "captured_at": captured_at,
        }
        return {**unsigned, "report_fingerprint": _fingerprint(unsigned)}


def validate_deployment_smoke_report(report: Mapping[str, Any]) -> tuple[str, ...]:
    required = {
        "artifact_kind",
        "report_version",
        "status",
        "project_root",
        "fixture",
        "source_count",
        "primary_fingerprint",
        "backup_fingerprint",
        "restored_fingerprint",
        "query_evidence_count",
        "query_fingerprint",
        "control_plane",
        "readiness_status",
        "local_readiness_blocked_checks",
        "external_readiness_blocked_checks",
        "external_access",
        "captured_at",
        "report_fingerprint",
    }
    errors = ["root_shape_invalid"] if set(report) != required else []
    if report.get("artifact_kind") != ARTIFACT_KIND or report.get("report_version") != REPORT_VERSION or report.get("status") != "DEPLOYMENT_SMOKE_CANDIDATE":
        errors.append("report_identity_invalid")
    for field in ("primary_fingerprint", "backup_fingerprint", "restored_fingerprint", "query_fingerprint", "report_fingerprint"):
        if not is_sha256(report.get(field)):
            errors.append("fingerprint_invalid:" + field)
    if report.get("backup_fingerprint") != report.get("restored_fingerprint"):
        errors.append("restore_fingerprint_mismatch")
    if report.get("control_plane") != "SQLITE_LOCAL_INITIALIZED" or report.get("readiness_status") != "DEPLOYMENT_READINESS_BLOCKED":
        errors.append("local_deployment_contract_invalid")
    if report.get("external_access") != "NOT_PERFORMED":
        errors.append("external_access_claim_invalid")
    for field in ("local_readiness_blocked_checks", "external_readiness_blocked_checks"):
        if not isinstance(report.get(field), list) or any(not isinstance(value, str) or not value for value in report[field]):
            errors.append("blocked_checks_invalid:" + field)
    unsigned = {key: report[key] for key in required if key != "report_fingerprint"}
    if report.get("report_fingerprint") != _fingerprint(unsigned):
        errors.append("report_fingerprint_mismatch")
    return tuple(errors)


def write_deployment_smoke(report: Mapping[str, Any], path: str | Path) -> None:
    errors = validate_deployment_smoke_report(report)
    if errors:
        raise DeploymentSmokeError("deployment_smoke_report_invalid:" + errors[0])
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(dict(report), ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8")


__all__ = [
    "ARTIFACT_KIND",
    "DeploymentSmokeError",
    "run_local_deployment_smoke",
    "validate_deployment_smoke_report",
    "write_deployment_smoke",
]
