"""Generate and verify a deterministic SPDX SBOM for the PMIRI candidate.

The lock remains the source of truth. This SBOM deliberately records package
identity and version but does not invent distribution hashes; a deployment
package mirror must add hash-pinned acquisition before external promotion.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import tomllib
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping


ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = ROOT / "requirements.lock"
PYPROJECT_PATH = ROOT / "pyproject.toml"
REPRODUCIBLE_SOURCE_DATE_EPOCH = 946684800
NAME_PATTERN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9_.-]*)==([0-9][A-Za-z0-9.+-]*)$")
DEPENDENCY_PATTERN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9_.-]*)(.*)$")


class SbomError(ValueError):
    """Raised when the lock or SBOM is inconsistent."""


def canonical_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def read_lock() -> dict[str, str]:
    locked: dict[str, str] = {}
    for line_number, raw_line in enumerate(LOCK_PATH.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = NAME_PATTERN.fullmatch(line)
        if match is None:
            raise SbomError(f"invalid_lock_line:{line_number}")
        name, version = match.groups()
        key = canonical_name(name)
        if key in locked:
            raise SbomError(f"duplicate_lock_package:{name}")
        locked[key] = version
    if not locked:
        raise SbomError("lock_is_empty")
    return locked


def read_project() -> tuple[str, str, dict[str, str], dict[str, str]]:
    document = tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))
    project = document.get("project", {})
    name = project.get("name")
    version = project.get("version")
    if not isinstance(name, str) or not isinstance(version, str):
        raise SbomError("project_identity_missing")
    runtime = _parse_dependencies(project.get("dependencies", []))
    build = _parse_dependencies(document.get("build-system", {}).get("requires", []))
    return name, version, runtime, build


def _parse_dependencies(items: object) -> dict[str, str]:
    if not isinstance(items, list):
        raise SbomError("dependency_list_invalid")
    result: dict[str, str] = {}
    for item in items:
        if not isinstance(item, str):
            raise SbomError("dependency_invalid")
        match = DEPENDENCY_PATTERN.fullmatch(item.strip())
        if match is None:
            raise SbomError("dependency_invalid:" + item)
        result[canonical_name(match.group(1))] = match.group(2)
    return result


def _package_id(name: str) -> str:
    return "SPDXRef-Package-" + canonical_name(name).replace("-", "_")


def _creation_time() -> str:
    # Keep the tracked SBOM and the wheel reproducibility contract on the same
    # explicit epoch.  A different value would create an artifact that is
    # deterministic in isolation but cannot be compared with the release
    # candidate generated by CI.
    import os

    try:
        epoch = int(os.environ.get("SOURCE_DATE_EPOCH", str(REPRODUCIBLE_SOURCE_DATE_EPOCH)))
    except ValueError as exc:
        raise SbomError("source_date_epoch_invalid") from exc
    if epoch != REPRODUCIBLE_SOURCE_DATE_EPOCH:
        raise SbomError(f"source_date_epoch_must_equal:{REPRODUCIBLE_SOURCE_DATE_EPOCH}")
    return datetime.fromtimestamp(epoch, tz=timezone.utc).isoformat().replace("+00:00", "Z")


def build_sbom(*, locked: Mapping[str, str] | None = None) -> dict[str, object]:
    locked_values = dict(locked or read_lock())
    project_name, project_version, runtime, build = read_project()
    if project_name != "pmiri":
        raise SbomError("unexpected_project_name")
    lock_fingerprint = hashlib.sha256(
        json.dumps(
            {"project": project_name, "version": project_version, "locked": locked_values},
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()
    packages: list[dict[str, object]] = [{
        "SPDXID": _package_id(project_name),
        "name": project_name,
        "versionInfo": project_version,
        "downloadLocation": "NOASSERTION",
        "filesAnalyzed": False,
        "licenseConcluded": "NOASSERTION",
        "licenseDeclared": "NOASSERTION",
        "supplier": "NOASSERTION",
    }]
    for name, version in sorted(locked_values.items()):
        packages.append({
            "SPDXID": _package_id(name),
            "name": name,
            "versionInfo": version,
            "downloadLocation": "NOASSERTION",
            "filesAnalyzed": False,
            "licenseConcluded": "NOASSERTION",
            "licenseDeclared": "NOASSERTION",
            "supplier": "NOASSERTION",
            "externalRefs": [{
                "referenceCategory": "PACKAGE-MANAGER",
                "referenceType": "purl",
                "referenceLocator": f"pkg:pypi/{name}@{version}",
            }],
        })
    relationships: list[dict[str, str]] = []
    root_id = _package_id(project_name)
    for name in sorted(runtime):
        relationships.append({"spdxElementId": root_id, "relationshipType": "DEPENDS_ON", "relatedSpdxElement": _package_id(name)})
    for name in sorted(build):
        relationships.append({"spdxElementId": _package_id(name), "relationshipType": "BUILD_DEPENDENCY_OF", "relatedSpdxElement": root_id})
    document_core = {
        "spdxVersion": "SPDX-2.3",
        "dataLicense": "CC0-1.0",
        "SPDXID": "SPDXRef-DOCUMENT",
        "name": "pmiri-candidate-sbom",
        "documentNamespace": f"urn:pmiri:sbom:{lock_fingerprint}",
        "creationInfo": {
            "created": _creation_time(),
            "creators": ["Tool: pmiri-sbom-generator/0.1"],
        },
        "documentComment": "Deterministic local candidate SBOM. Distribution hashes are NOASSERTION until the deployment package mirror supplies hash-pinned lock entries.",
        "packages": packages,
        "relationships": relationships,
    }
    return document_core


def verify_sbom(
    document: Mapping[str, Any],
    *,
    locked: Mapping[str, str] | None = None,
    announce: bool = True,
) -> tuple[str, ...]:
    locked_values = dict(locked or read_lock())
    project_name, project_version, _runtime, _build = read_project()
    errors: list[str] = []
    if document.get("spdxVersion") != "SPDX-2.3":
        errors.append("spdx_version_invalid")
    if document.get("SPDXID") != "SPDXRef-DOCUMENT":
        errors.append("document_id_invalid")
    expected_namespace = "urn:pmiri:sbom:" + hashlib.sha256(
        json.dumps(
            {"project": project_name, "version": project_version, "locked": locked_values},
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()
    if document.get("documentNamespace") != expected_namespace:
        errors.append("document_namespace_invalid")
    packages = document.get("packages")
    if not isinstance(packages, list):
        return ("packages_invalid",)
    by_name = {item.get("name"): item for item in packages if isinstance(item, dict)}
    expected_names = {"pmiri", *locked_values}
    if set(by_name) != expected_names:
        errors.append("package_inventory_mismatch")
    for name, version in locked_values.items():
        package = by_name.get(name)
        if not isinstance(package, dict) or package.get("versionInfo") != version:
            errors.append(f"package_version_mismatch:{name}")
        elif package.get("downloadLocation") != "NOASSERTION":
            errors.append(f"download_location_unexpected:{name}")
        refs = package.get("externalRefs", [])
        expected_purl = f"pkg:pypi/{name}@{version}"
        if not any(isinstance(ref, dict) and ref.get("referenceLocator") == expected_purl for ref in refs):
            errors.append(f"purl_missing:{name}")
    if not isinstance(by_name.get("pmiri"), dict):
        errors.append("project_package_missing")
    elif by_name["pmiri"].get("versionInfo") != project_version:
        errors.append("project_version_mismatch")
    relationships = document.get("relationships")
    if not isinstance(relationships, list):
        errors.append("relationships_invalid")
    if not errors and announce:
        print(f"SBOM verified: {len(locked_values)} locked packages plus pmiri")
    return tuple(errors)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="artifacts/sbom/pmiri-sbom.spdx.json")
    parser.add_argument("--check", action="store_true", help="verify an existing deterministic SBOM without writing")
    args = parser.parse_args(argv)
    try:
        locked = read_lock()
        expected = build_sbom(locked=locked)
        output = (ROOT / args.output).resolve() if not Path(args.output).is_absolute() else Path(args.output)
        if args.check:
            actual = json.loads(output.read_text(encoding="utf-8"))
            if actual != expected:
                print("sbom_not_deterministic_or_stale", file=sys.stderr)
                return 1
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(json.dumps(expected, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8")
        errors = verify_sbom(expected, locked=locked)
    except (OSError, json.JSONDecodeError, tomllib.TOMLDecodeError, SbomError) as exc:
        print(f"SBOM verification failed: {exc}", file=sys.stderr)
        return 1
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    print(f"SBOM path: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
